hibernate:
  default_schema: public

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pmda
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

trackers:
  -
    type: jira
    localId: 1
    clientId: 10000
    url:
    user:
    password:
  -
    type: jira
    localId: 2
    clientId: 50
    url: https://test2.atlassian.net/rest/api/3/
    user: "user2"
    password: "user2"

logging:
  level:
    root: INFO
    liquibase: INFO
