hibernate:
  default_schema: public

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/pmda
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

tracker:
  jira:
    url:
    user:
    password:

logging:
  level:
    root: DEBUG
    liquibase: DEBUG
