hibernate:
  default_schema: public

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      show-sql: false
#      show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pmda
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

tracker:
  jira:
    1:
      url: https://herubel.atlassian.net/rest/api/3/
      user: "julien@herubel.com"
      password: "KxmWqia8pY0XXUMws60M0217"

logging:
  level:
    root: INFO
#    root: DEBUG
    liquibase: INFO
#    liquibase: DEBUG
