spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pmda
    username: postgres
    password: $POSTGRES_PASSWORD
    driver-class-name: org.postgresql.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

tracker:
  jira:
    user: null
    password: null