hibernate:
  default_schema: public

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pmda
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

trackers:
  -
    type: jira
    localId: 1
    clientId: 10842
    url: https://pmda-test.atlassian.net/rest/api/3/
    user: "pmda@email.com"
    password: "userToken"