scheduler:
  enabled: true
  trigger:
    issue-update-cron-expression: "0 0/1 * 1/1 * ? *"
    project-update-cron-expression: "0 0/30 * 1/1 * ? *"

spring:
  batch:
    initialize-schema: always
    job:
      enabled: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      show-sql: false
      ddl-auto: none

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    root: ERROR
    liquibase: ERROR

tracker:
  value: mantis
