spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pmda
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

tracker:
  jira:
    user: "julien@herubel.com"
    password: "KxmWqia8pY0XXUMws60M0217"