hibernate:
  default_schema: public

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      show-sql: false
#      show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pmda
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

trackers:
  -
    type: jira
    number: 1
    url: https://test1.atlassian.net/rest/api/3/
    user: "user1"
    password: "user1"
  -
    type: jira
    number: 2
    url: https://test2.atlassian.net/rest/api/3/
    user: "user2"
    password: "user2"

logging:
  level:
    root: INFO
#    root: DEBUG
    liquibase: INFO
#    liquibase: DEBUG
