scheduler:
  enabled: true
  trigger:
    project-update-cron-expression: "0 0/1 * 1/1 * ? *"
    project-retry-cron-expression: "0 0/1 * 1/1 * ? *"
    project-max-retry: 5
    #project-retry-cron-expression: "0 0 0/1 1/1 * ? *"

spring:
  batch:
    initialize-schema: always
    job:
      enabled: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    root: INFO
    liquibase: INFO